language: php

php:
  - 7.0
  - 7.1

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer update $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit -vvv

