#<?php
#/**
# * PHP Layout Drupal module hook definitions and module placeholder.
# */
#
#/**
# * Layout edit token get parameter name
# */
#const PHP_LAYOUT_TOKEN_PARAMETER = 'layout-edit';
#
#/**
# * Edit all permission
# */
#const PHP_LAYOUT_PERMISSION_EDIT_ALL = 'edit all layouts';
#
#/**
# * Implements hook_menu().
# */
#function phplayout_menu() {
#  $items = [];
#
#  // Token control actions
#  $items['layout/callback/control/edit-one'] = [
#    'page callback' => 'sf_dic_page',
#    'page arguments' => ['php_layout.admin_layout_controller::editSingle'],
#  ];
#  $items['layout/callback/control/commit-one'] = [
#    'page callback' => 'sf_dic_page',
#    'page arguments' => ['php_layout.admin_layout_controller::commitSingle'],
#  ];
#  $items['layout/callback/control/rollback-one'] = [
#    'page callback' => 'sf_dic_page',
#    'page arguments' => ['php_layout.admin_layout_controller::rollbackSingle'],
#  ];
#  $items['layout/callback/control/commit'] = [
#    'page callback' => 'sf_dic_page',
#    'page arguments' => ['php_layout.admin_layout_controller::commitAll'],
#  ];
#  $items['layout/callback/control/rollback'] = [
#    'page callback' => 'sf_dic_page',
#    'page arguments' => ['php_layout.admin_layout_controller::rollbackAll'],
#  ];
#
#  // More specific callbacks
#  $items['layout/callback/set-page'] = [
#    'page callback' => 'sf_dic_page',
#    'page arguments' => ['php_layout.drupal_layout_controller::setPage'],
#  ];
#
#  return $items;
#}

layout_ajax_add_column_container:
    path: /layout/ajax/add-column-container
    defaults: { _controller: 'php_layout.edit_controller:addColumnContainerAction' }

layout_ajax_add_column:
    path: /layout/ajax/add-column
    defaults: { _controller: 'php_layout.edit_controller:addColumnAction' }

layout_ajax_add_item:
    path: /layout/ajax/add-item
    defaults: { _controller: 'php_layout.edit_controller:addAction' }

layout_ajax_get_styles:
    path: /layout/ajax/get-styles
    defaults: { _controller: 'php_layout.edit_controller:getAllowedStylesAction' }

layout_ajax_move:
    path: /layout/ajax/move
    defaults: { _controller: 'php_layout.edit_controller:moveAction' }

layout_ajax_remove:
    path: /layout/ajax/remove
    defaults: { _controller: 'php_layout.edit_controller:removeAction' }

layout_ajax_render:
    path: /layout/ajax/render
    defaults: { _controller: 'php_layout.edit_controller:renderAction' }

layout_ajax_set_style:
    path: /layout/ajax/set-style
    defaults: { _controller: 'php_layout.edit_controller:setStyleAction' }
