#
# Core API services, without any concrete implementation
#
# Those two services needs to be defined by your business API:
#   - php_layout.token_storage : TokenLayoutStorageInterface
#   - php_layout.storage : LayoutStorageInterface
#
services:

    php_layout.type_registry:
        public: false
        class: MakinaCorpus\Layout\Type\ItemTypeRegistry

    php_layout.renderer:
        public: true
        class: MakinaCorpus\Layout\Render\Renderer
        arguments: ['@php_layout.type_registry', '@php_layout.grid_renderer']

    php_layout.token_generator:
        public: false
        class: MakinaCorpus\Layout\Controller\DefaultTokenGenerator

    php_layout.context:
        public: true
        class: MakinaCorpus\Layout\Controller\Context
        arguments: ['@php_layout.storage', '@php_layout.token_storage', '@php_layout.token_generator']

    php_layout.edit_controller:
        # Drupal 8 form implementation needs this to be public
        # All other implementations won't care a bit
        public: true
        class: MakinaCorpus\Layout\Controller\EditController
        arguments: ['@php_layout.token_storage', '@php_layout.type_registry', '@php_layout.renderer']

    php_layout.grid_renderer:
        # Drupal 8 form implementation needs this to be public
        # All other implementations won't care a bit
        public: true
        class: MakinaCorpus\Layout\Render\BootstrapGridRenderer
