#
# Symfony specific services, might be used by Drupal too
#
services:

    php_layout.argument_value_resolver.edit_token:
        class: MakinaCorpus\Layout\Controller\EditTokenArgumentValueResolver
        public: false
        arguments: ["@php_layout.token_storage"]
        tags: [{name: controller.argument_value_resolver, priority: 128}]

    php_layout.argument_value_resolver.layout:
        class: MakinaCorpus\Layout\Controller\LayoutArgumentValueResolver
        public: false
        arguments: ["@php_layout.context", "@php_layout.storage"]
        tags: [{name: controller.argument_value_resolver, priority: 128}]
