#
# Symfony specific services, might be used by Drupal too
#
services:

    php_layout.argument_value_resolver.context:
        class: MakinaCorpus\Layout\Controller\ArgumentResolver\ContextValueResolver
        public: false
        arguments: ["@php_layout.context"]
        tags: [{name: controller.argument_value_resolver, priority: 128}]

    php_layout.argument_value_resolver.edit_token:
        class: MakinaCorpus\Layout\Controller\ArgumentResolver\EditTokenValueResolver
        public: false
        arguments: ["@php_layout.context"]
        tags: [{name: controller.argument_value_resolver, priority: 128}]

    php_layout.argument_value_resolver.layout:
        class: MakinaCorpus\Layout\Controller\ArgumentResolver\LayoutValueResolver
        public: false
        arguments: ["@php_layout.context"]
        tags: [{name: controller.argument_value_resolver, priority: 128}]

    php_layout.kernel_event_subscriber:
        public: true
        class: MakinaCorpus\Layout\EventDispatcher\KernelEventSubscriber
        arguments: ['@php_layout.context', '@event_dispatcher']
        tags: [{name: kernel.event_subscriber}]
